---
title: "Change"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
rm(list = ls())

library('dplyr')
library('ggplot2')
```


Load and manipulate data

```{r}
library(nycflights13)

str(flights)
```

## Time-Series Calendar Heatmap

**How can we quickly analyze daily departure delay over the entire data set?**


Data preparation

```{r}
library(lubridate)

avg_delays <- flights %>%
  filter(dep_delay < 60) %>%
  group_by(origin, time_hour) %>%
  summarize(avg_delay = mean(dep_delay, na.rm = TRUE)) %>%
  mutate(hour = hour(time_hour),
         month = month(time_hour, label = TRUE, abbr = TRUE),
         week_day = wday(time_hour, label = TRUE, abbr = TRUE)) %>%
  filter(week_day %in% c('Mon','Tue','Wed','Thu','Fri')) %>%
  filter(hour %in% c(6,12,18,23))
```

Heatmap

```{r}
ggplot(avg_delays, aes(origin, week_day, fill = avg_delay)) + 
  geom_tile(colour = "white") + 
  facet_grid(hour~month) + 
  scale_fill_gradient(low="red", high="green") +
  labs(x="Airport of Origin",
       y="",
       title = "Time-Series Departure Delay Heatmap", 
       subtitle="NYC Flights 2013", 
       fill="Delays") +
  theme_bw() +
  theme(axis.text.x = element_text(colour="grey20", size=10, angle=90, hjust=.5, vjust=.5),
        axis.text.y = element_text(colour="grey20", size=10))
```